### ISSUE TITLE
BBOX query specification

### ISSUE THREAD

**Issue by emiliom** [ioos/i52n-sos#25]
The IOOS SOS WSDD documents describe how a BBOX query must be encoded, if implemented. See [here under `featureOfInterest`](http://ioos.github.io/sos-guidelines/doc/wsdd/sos_wsdd_github_notoc/#getobservation-request). That's one of the request styles I tried, at least against the NANOOS i52n SOS. As there may be a problem in the i52n BBOX query implementation relative to the IOOS specifications, I'm bringing here the email list thread I started (["How to specify BBOX query in GetObservation GET request"](https://groups.google.com/forum/#!topic/i52n-sos/1qpGt4zfBs8)).

**Comment by emiliom** [comment]
@shane-axiom, have you had a chance to look into this? Just documenting what GET/kvp BBOX querying mechanism i52n sos currently supports would be helpful at this stage.

**Comment by shane-axiom** [comment]
Long story short, 52North implemented the SOS 2.0 GetObservation KVP specification's spatialFiltering in the 52n SOS, and (mostly) backported it to work with SOS 1.0 (since SOS 1.0 doesn't actually have any KVP specification). See section __13.2.3 GetObservation KVP Binding__ of the SOS 2.0 specification (12-006) for details and an example.

I'd include the specification's example, but apparently it's an image inside of a PDF. Yay accessibility.

Here's a relevant section:

> Requirement 116 For the KVP binding, a bounding box shall be used as the spatialFilter as
defined in the conceptual model of the GetObservation operation (Subclause 8.3).
The encoding of the bounding box shall be a list of comma separated values. The first value shall be the valueReference of the spatial property of the observations to which this bounding box, as a
spatial filter, is applied – following the requirements on ValueReference as defined by [ISO 19143] / [OGC 09-026r1].
>
>The following values shall be as defined in Subclause 10.2.3 of [OGC 06-121r3].
>
>This results in the following encoding:
>valueReference,minCoordinate1,minCoordinate2,...,minCoordinateN,maxCoordinate1,maxCoordinate2,...,maxCoordinateN,crsURI


Here's an SOS 2.0 example against the NANOOS SOS:

http://data.nanoos.org/52nsos/service?service=SOS&version=2.0.0&request=GetObservation&namespaces=xmlns(sams%2Chttp%3A%2F%2Fwww.opengis.net%2FsamplingSpatial%2F2.0)%2Cxmlns(om%2Chttp%3A%2F%2Fwww.opengis.net%2Fom%2F2.0)&spatialFilter=om%3AfeatureOfInterest%2F*%2Fsams%3Ashape%2C47.7%2C-122.4%2C47.8%2C-122.3%2Chttp%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F4326&temporalFilter=om:phenomenonTime,2016-01-21T00:00:00Z/2016-01-21T02:00:00Z

Note the url encoded namespaces, spatialFilter, and temporalFilter. Unencoded, the spatialFilter looks like:

    om:featureOfInterest/*/sams:shape,47.7,-122.4,47.8,-122.3,http://www.opengis.net/def/crs/EPSG/0/4326

Note: As according to the spec, EPSG 4326 is assumed to be the default if no EPSG is specified, so this also works: 

om:featureOfInterest/*/sams:shape,47.7,-122.4,47.8,-122.3

There are no spatialFilter or temporalFilter parameters for SOS 1.0, so they become featureOfInterest and eventTime respectively.

NANOOS SOS 1.0 example return IOOS format:

http://data.nanoos.org/52nsos/service?service=SOS&version=1.0.0&request=GetObservation&offering=urn:ioos:network:nanoos:all&procedure=urn:ioos:network:nanoos:all&observedProperty=http://mmisw.org/ont/cf/parameter/air_temperature&featureOfInterest=om%3AfeatureOfInterest%2F*%2Fsams%3Ashape%2C47.0%2C-123.0%2C48.0%2C-122.0%2Chttp%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F4326&eventTime=om:phenomenonTime,2016-01-21T00:00:00Z/2016-01-21T02:00:00Z&responseFormat=text%2Fxml%3B%20subtype%3D%22om%2F1.0.0%2Fprofiles%2Fioos_sos%2F1.0%22

**Comment by emiliom** [comment]
Thank you!! And yikes all around.

I'm relieved to see that there is a KVP mechanism for effectively requesting a BBOX spatial filter, and that it at least involves `featureOfInterest`, even if it [doesn't conform to what's stated in the IOOS SOS WSDD](http://ioos.github.io/sos-guidelines/doc/wsdd/sos_wsdd_github_notoc/#getobservation-request:638e0b263020c13a76a55332bd966dbe). At least it means that we may be able to hack it into pyoos w/o too much trouble, I think.

For reference, what you've found is that this works with i52n sos 1.0:
```
featureOfInterest=om:featureOfInterest/*/sams:shape,47.7,-122.4,47.8,-122.3
```
while the IOOS SOS WSDD states that it should instead be like this:
```
featureOfInterest=BBOX:47.7,-122.4,47.8,-122.3
```

Also for reference, I'm copying below the simplest possible, valid sample request, adapted from your last url example from the NANOOS SOS 1.0 (the only change is that I removed the EPSG specification, to let the default kick in, per your comment):
http://data.nanoos.org/52nsos/service?service=SOS&version=1.0.0&request=GetObservation&offering=urn:ioos:network:nanoos:all&procedure=urn:ioos:network:nanoos:all&observedProperty=http://mmisw.org/ont/cf/parameter/air_temperature&featureOfInterest=om%3AfeatureOfInterest%2F*%2Fsams%3Ashape%2C47.0%2C-123.0%2C48.0%2C-122.0&eventTime=om:phenomenonTime,2016-01-21T00:00:00Z/2016-01-21T02:00:00Z&responseFormat=text%2Fxml%3B%20subtype%3D%22om%2F1.0.0%2Fprofiles%2Fioos_sos%2F1.0%22

**Comment by abirger** [comment]
@emiliom , I will dig into the WSDD mismatch early next week as soon as I finish with shoveling those 24 inches of snow from my deck, porch and around the car...

**Comment by emiliom** [comment]
Thanks, @abirger. Good luck with the snow.

**Comment by abirger** [comment]
@emiliom , @shane-axiom , although this issue has been closed, I will leave one more comment here. The 52N injection of SOS 2.0 spatial and temporal filtering into SOS 1.0 demonstrates a somewhat inconsistent behavior in the SOS v1.0 requests:
 * spatial filtering only allows the SOS 2.0 format, i.e. `featureOfInterest=om:featureOfInterest/*/sams:shape,47.7,-122.4,47.8,-122.3`; 
 * temporal filtering tolerates both SOS 2.0 representation `eventTime=om:phenomenonTime,2016-01-21T00:00:00Z/2016-01-21T02:00:00Z` as well as the shorter SOS 1.0 representation, i.e. `eventTime=2016-01-21T00:00:00Z/2016-01-21T02:00:00Z`.

@emiliom , I believe that the description of BBOX in the WSDD has been non-critically adopted from the CO-OPS and NDBC SOS implementations, which at that moment just followed the current OGC & OOSTethys Best Practices: as the BBOX was not defined in the SOS spec, it was suggested that `featureOfInterest` BBOX uses the approach recommended in section 10.2.3 of OGC 06-121r3.

Anyway, I will fix the description and add the proper examples.

**Comment by emiliom** [comment]
@shane-axiom, I didn't realize you were going to modify i52n sos to support the IOOS WSDD `featureOfInterest BBOX` specification. Cool, thanks! Are you implementing with the IOOS WSDD axis order (lon,lat)? I would think it should be done that way to be fully consistent.

@abirger thanks for your insightful input and guidance on this topic, too. Is it necessary to modify the WSDD document at this point, if SOS 2.0 is not mentioned much throughout the document? I can't remember whether it is or isn't, but if it's not, it's probably better to leave things as is for now.

**Comment by abirger** [comment]
@emiliom , the WSDD describes the IOOS Convention as the one that "contains additional constraints, definitions, requirements and “best practice” sort of recommendations that SOS 1.0.0 lacks; for future transition, the Convention follows SOS 2.0 requirements and definitions wherever they have been considered applicable, and do not contradict the SOS 1.0.0 specification." It also mentioned that "the provisions of the IOOS Convention are captured in the IOOS SOS Templates, and described further in this document." 

Actually, there is a handful of places throughout the WSDD where SOS 2.0 differences are explained, namely in the description of `procedure`, `acceptVersions`, and `eventTime`. So, this case will not be something extraordinary. Just an uncommon one...

**Comment by emiliom** [comment]
Ah. Good to know, thanks.

**Comment by abirger** [comment]
@emiliom , please check the updated description of [GetObservation request](http://ioos.github.io/sos-guidelines/doc/wsdd/sos_wsdd_github_notoc/#getobservation-request:638e0b263020c13a76a55332bd966dbe).

**Comment by emiliom** [comment]
@abirger, I don't really remember what that section of the document was like before your edits. I think I can see that the block that illustrates "HTTP/GET and HTTP/POST GetObservation requests" is new, and that looks like a helpful addition.

Above it, I think the table row describing `featureOfInterest` may be conflating i52n sos v1.0.1 with "IOOS SOS v1.0.1" when it states this:
> Until v1.0.1, the IOOS SOS did not support GetObservation KVP GET request with a BBOX constraint, i.e. featureOfInterest=BBOX:min_lon,min_lat,max_lon,max_lat in the request was not allowed, and BBOX could be specified only in the POST request. Starting with v1.0.1, IOOS SOS supports two ways of BBOX constraint in the GET request.

My understanding was that the WSDD was clear about how featureOfInterest=BBOX should be specified, but i52n sos <= 1.0 did not implemented it that way (irrespective of whether the IOOS SOS specification was a wise and well informed choice!).

**Comment by abirger** [comment]
@emiliom , oops, my bad! I did not actually proofread the table entry upon correction. I need to correct the the table to indicate that the i52N below 1.0.1 actually does support the BBOX but in SOS 2.0 style.
